name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout abystoma/external-workflow
      - name: Greetings
        run: echo "$(<greetings.txt)"
